version: '3.8'
services:
  backend:
    build: ./backend # Assicurati che il percorso punti alla directory con il Dockerfile del backend
    ports:
      - "8080:8080" # Sostituisci con la porta che il tuo backend ascolta se diversa da 8000
    networks:
      - app-network

  frontend:
    build: ./frontend # Assicurati che il percorso punti alla directory con il Dockerfile del frontend
    ports:
      - "3000:3000" # Sostituisci con la porta che il tuo frontend ascolta se diversa da 3000
    environment:
      - BACKEND_URL=http://backend:8080 # Sostituisci con la variabile d'ambiente che il tuo frontend utilizza per collegarsi al backend
    networks:
      - app-network

  redis:
      image: "redis:alpine"
      command: redis-server --requirepass password
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data

networks:
  app-network:

volumes:
  redis-data: