version: '3.8'
services:
  backend:
    build: ./backend # Assicurati che il percorso punti alla directory con il Dockerfile del backend
    ports:
      - "8080:8080" # Sostituisci con la porta che il tuo backend ascolta se diversa da 8000
    networks:
      - app-network

  frontend:
    build: ./frontend # Assicurati che il percorso punti alla directory con il Dockerfile del frontend
    ports:
      - "3000:3000" # Sostituisci con la porta che il tuo frontend ascolta se diversa da 3000
    environment:
      - BACKEND_URL=http://backend:8080 # Sostituisci con la variabile d'ambiente che il tuo frontend utilizza per collegarsi al backend
    networks:
      - app-network

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

networks:
  app-network:

volumes:
  db-data: