version: '3.8'

#@danmig06 for access to an service with the ip not use the IP but the name of image like "http://backend:8080" 

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    depends_on:
      redis:
        condition: service_healthy

  redis:
      image: "redis:alpine"
      command: redis-server --requirepass password
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  redis-data: