name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: '21.x' # Aggiunte versioni multiple come esempio
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        # La configurazione del percorso di cache non è necessaria per npm con actions/setup-node@v3 se lavori nel working-directory corretto
      
    - run: npm ci
      working-directory: frontend
    - run: npm run build --if-present
      working-directory: frontend
    - run: npm test
      working-directory: frontend
